/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author diego
 */
public class SistemaFacturaFinal extends javax.swing.JFrame {

    /**
     * Creates new form SistemaFacturaFinal
     */
    public SistemaFacturaFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        pn_panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInventario = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mn_factura = new javax.swing.JMenu();
        mnu_factura = new javax.swing.JMenuItem();
        mn_factura1 = new javax.swing.JMenu();
        mnu_login = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pn_panelLayout = new javax.swing.GroupLayout(pn_panel);
        pn_panel.setLayout(pn_panelLayout);
        pn_panelLayout.setHorizontalGroup(
            pn_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        pn_panelLayout.setVerticalGroup(
            pn_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        mnuInventario.setText("Inventario");

        mnuUsuarios.setText("Cliente");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuInventario.add(mnuUsuarios);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        mnuInventario.add(mnuEmpleados);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        mnuInventario.add(mnuProductos);

        jMenuBar1.add(mnuInventario);

        mn_factura.setText("Factura");

        mnu_factura.setText("Factura");
        mnu_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_facturaActionPerformed(evt);
            }
        });
        mn_factura.add(mnu_factura);

        jMenuBar1.add(mn_factura);

        mn_factura1.setText("Login");

        mnu_login.setText("Login");
        mnu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_loginActionPerformed(evt);
            }
        });
        mn_factura1.add(mnu_login);

        jMenuBar1.add(mn_factura1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_panel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_panel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        // TODO add your handling code here:
        this.mostrarFormulario(new SistemaProductos());
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:
        this.mostrarFormulario(new SistemaCliente());
        
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnu_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_facturaActionPerformed
        // TODO add your handling code here:
        this.mostrarFormulario(new SistemaFacturas());
    }//GEN-LAST:event_mnu_facturaActionPerformed

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        // TODO add your handling code here:
        this.mostrarFormulario(new SistemaEmpleado());
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_loginActionPerformed
        // TODO add your handling code here:
        this.mostrarFormulario(new SistemaLogin());
    }//GEN-LAST:event_mnu_loginActionPerformed

    /**S
     * @param args the command line argumentsSS
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaFacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaFacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaFacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaFacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaFacturaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mn_factura;
    private javax.swing.JMenu mn_factura1;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JMenuItem mnu_factura;
    private javax.swing.JMenuItem mnu_login;
    private javax.swing.JDesktopPane pn_panel;
    // End of variables declaration//GEN-END:variables

    private void mostrarFormulario(JInternalFrame frm) {
        try {
            frm.setMaximum(true);
            frm.setClosable(true);
            frm.setVisible(true);
            this.pn_panel.add(frm);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(SistemaFacturaFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
